name: Build Pico Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install ARM GCC toolchain and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake build-essential ninja-build

    - name: Clone Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init

    - name: Configure project with CMake
      run: cmake -B build -S . -DPICO_SDK_PATH=$PWD/pico-sdk -DCMAKE_BUILD_TYPE=Release -G Ninja

    - name: Build project
      run: cmake --build build
