name: Build Pico Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # 下载并设置 pico-sdk
    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git pico-sdk
        cd pico-sdk
        git submodule update --init
      shell: bash

    - name: Configure build
      run: cmake -B build -S . -DPICO_SDK_PATH=$PWD/pico-sdk

    - name: Build
      run: cmake --build build
