name: Build Pico Project with Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build build-essential git

    - name: Clone Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        cd pico-sdk
        git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B build -S . -DPICO_SDK_PATH=$PWD/pico-sdk -G Ninja

    - name: Build with Ninja
      run: cmake --build build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pico-build-artifacts
        path: build/
